export const ASelectStylePluginOptions = {
  propsDefault: {

  },
  cssClasses: [
    {
      label: "_A_SELECT_STYLES_VALUE_D_INLINE_",
      value: "a_d_inline",
      group: "display",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_INLINE_",
      value: "a_d_inline_mobile",
      group: "display",
      subGroup: "mobile",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_MOBILE_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_INLINE_",
      value: "a_d_inline_tablet",
      group: "display",
      subGroup: "tablet",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_TABLET_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_INLINE_",
      value: "a_d_inline_touch",
      group: "display",
      subGroup: "touch",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_TOUCH_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_INLINE_",
      value: "a_d_inline_desktop",
      group: "display",
      subGroup: "desktop",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_DESKTOP_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_INLINE_",
      value: "a_d_inline_widescreen",
      group: "display",
      subGroup: "widescreen",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_WIDESCREEN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_INLINE_",
      value: "a_d_inline_fullhd",
      group: "display",
      subGroup: "fullhd",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_FULLHD_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_INLINE_",
      value: "a_d_inline_large",
      group: "display",
      subGroup: "large",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_LARGE_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_INLINE_BLOCK_",
      value: "a_d_inline_block",
      group: "display",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_INLINE_BLOCK_",
      value: "a_d_inline_block_mobile",
      group: "display",
      subGroup: "mobile",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_MOBILE_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_INLINE_BLOCK_",
      value: "a_d_inline_block_tablet",
      group: "display",
      subGroup: "tablet",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_TABLET_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_INLINE_BLOCK_",
      value: "a_d_inline_block_touch",
      group: "display",
      subGroup: "touch",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_TOUCH_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_INLINE_BLOCK_",
      value: "a_d_inline_block_desktop",
      group: "display",
      subGroup: "desktop",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_DESKTOP_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_INLINE_BLOCK_",
      value: "a_d_inline_block_widescreen",
      group: "display",
      subGroup: "widescreen",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_WIDESCREEN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_INLINE_BLOCK_",
      value: "a_d_inline_block_fullhd",
      group: "display",
      subGroup: "fullhd",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_FULLHD_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_INLINE_BLOCK_",
      value: "a_d_inline_block_large",
      group: "display",
      subGroup: "large",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_LARGE_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_BLOCK_",
      value: "a_d_block",
      group: "display",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_BLOCK_",
      value: "a_d_block_mobile",
      group: "display",
      subGroup: "mobile",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_MOBILE_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_BLOCK_",
      value: "a_d_block_tablet",
      group: "display",
      subGroup: "tablet",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_TABLET_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_BLOCK_",
      value: "a_d_block_touch",
      group: "display",
      subGroup: "touch",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_TOUCH_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_BLOCK_",
      value: "a_d_block_desktop",
      group: "display",
      subGroup: "desktop",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_DESKTOP_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_BLOCK_",
      value: "a_d_block_widescreen",
      group: "display",
      subGroup: "widescreen",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_WIDESCREEN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_BLOCK_",
      value: "a_d_block_fullhd",
      group: "display",
      subGroup: "fullhd",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_FULLHD_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_BLOCK_",
      value: "a_d_block_large",
      group: "display",
      subGroup: "large",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_LARGE_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_FLEX_",
      value: "a_d_flex",
      group: "display",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_FLEX_",
      value: "a_d_flex_mobile",
      group: "display",
      subGroup: "mobile",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_MOBILE_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_FLEX_",
      value: "a_d_flex_tablet",
      group: "display",
      subGroup: "tablet",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_TABLET_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_FLEX_",
      value: "a_d_flex_touch",
      group: "display",
      subGroup: "touch",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_TOUCH_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_FLEX_",
      value: "a_d_flex_desktop",
      group: "display",
      subGroup: "desktop",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_DESKTOP_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_FLEX_",
      value: "a_d_flex_widescreen",
      group: "display",
      subGroup: "widescreen",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_WIDESCREEN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_FLEX_",
      value: "a_d_flex_fullhd",
      group: "display",
      subGroup: "fullhd",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_FULLHD_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_FLEX_",
      value: "a_d_flex_large",
      group: "display",
      subGroup: "large",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_LARGE_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_INLINE_FLEX_",
      value: "a_d_inline_flex",
      group: "display",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_INLINE_FLEX_",
      value: "a_d_inline_flex_mobile",
      group: "display",
      subGroup: "mobile",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_MOBILE_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_INLINE_FLEX_",
      value: "a_d_inline_flex_tablet",
      group: "display",
      subGroup: "tablet",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_TABLET_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_INLINE_FLEX_",
      value: "a_d_inline_flex_touch",
      group: "display",
      subGroup: "touch",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_TOUCH_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_INLINE_FLEX_",
      value: "a_d_inline_flex_desktop",
      group: "display",
      subGroup: "desktop",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_DESKTOP_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_INLINE_FLEX_",
      value: "a_d_inline_flex_widescreen",
      group: "display",
      subGroup: "widescreen",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_WIDESCREEN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_INLINE_FLEX_",
      value: "a_d_inline_flex_fullhd",
      group: "display",
      subGroup: "fullhd",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_FULLHD_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_INLINE_FLEX_",
      value: "a_d_inline_flex_large",
      group: "display",
      subGroup: "large",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_LARGE_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_NONE_",
      value: "a_d_none",
      group: "display",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_NONE_",
      value: "a_d_none_mobile",
      group: "display",
      subGroup: "mobile",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_MOBILE_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_NONE_",
      value: "a_d_none_tablet",
      group: "display",
      subGroup: "tablet",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_TABLET_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_NONE_",
      value: "a_d_none_touch",
      group: "display",
      subGroup: "touch",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_TOUCH_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_NONE_",
      value: "a_d_none_desktop",
      group: "display",
      subGroup: "desktop",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_DESKTOP_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_NONE_",
      value: "a_d_none_widescreen",
      group: "display",
      subGroup: "widescreen",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_WIDESCREEN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_NONE_",
      value: "a_d_none_fullhd",
      group: "display",
      subGroup: "fullhd",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_FULLHD_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_D_NONE_",
      value: "a_d_none_large",
      group: "display",
      subGroup: "large",
      groupName: "_A_SELECT_STYLES_GROUP_DISPLAY_",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_LARGE_",
    },

    {
      label: "_A_SELECT_STYLES_VALUE_FLEX_ROW_",
      value: "a_flex_row",
      group: "flex",
      groupName: "_A_SELECT_STYLES_GROUP_FLEX_",
      subGroup: "flex_direction",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_FLEX_DIRECTION_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_FLEX_COLUMN_",
      value: "a_flex_column",
      group: "flex",
      groupName: "_A_SELECT_STYLES_GROUP_FLEX_",
      subGroup: "flex_direction",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_FLEX_DIRECTION_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_FLEX_ROW_REVERSE_",
      value: "a_flex_row_reverse",
      group: "flex",
      groupName: "_A_SELECT_STYLES_GROUP_FLEX_",
      subGroup: "flex_direction",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_FLEX_DIRECTION_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_FLEX_COLUMN_REVERSE_",
      value: "a_flex_column_reverse",
      group: "flex",
      groupName: "_A_SELECT_STYLES_GROUP_FLEX_",
      subGroup: "flex_direction",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_FLEX_DIRECTION_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_JUSTIFY_CONTENT_START_",
      value: "a_justify_content_start",
      group: "flex",
      groupName: "_A_SELECT_STYLES_GROUP_FLEX_",
      subGroup: "justify_content",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_JUSTIFY_CONTENT_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_JUSTIFY_CONTENT_END_",
      value: "a_justify_content_end",
      group: "flex",
      groupName: "_A_SELECT_STYLES_GROUP_FLEX_",
      subGroup: "justify_content",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_JUSTIFY_CONTENT_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_JUSTIFY_CONTENT_CENTER_",
      value: "a_justify_content_center",
      group: "flex",
      groupName: "_A_SELECT_STYLES_GROUP_FLEX_",
      subGroup: "justify_content",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_JUSTIFY_CONTENT_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_JUSTIFY_CONTENT_BETWEEN_",
      value: "a_justify_content_between",
      group: "flex",
      groupName: "_A_SELECT_STYLES_GROUP_FLEX_",
      subGroup: "justify_content",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_JUSTIFY_CONTENT_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_JUSTIFY_CONTENT_AROUND_",
      value: "a_justify_content_around",
      group: "flex",
      groupName: "_A_SELECT_STYLES_GROUP_FLEX_",
      subGroup: "justify_content",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_JUSTIFY_CONTENT_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_JUSTIFY_CONTENT_EVENLY_",
      value: "a_justify_content_evenly",
      group: "flex",
      groupName: "_A_SELECT_STYLES_GROUP_FLEX_",
      subGroup: "justify_content",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_JUSTIFY_CONTENT_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_ALIGN_ITEMS_START_",
      value: "a_align_items_start",
      group: "flex",
      groupName: "_A_SELECT_STYLES_GROUP_FLEX_",
      subGroup: "align_items",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_ALIGN_ITEMS_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_ALIGN_ITEMS_END_",
      value: "a_align_items_end",
      group: "flex",
      groupName: "_A_SELECT_STYLES_GROUP_FLEX_",
      subGroup: "align_items",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_ALIGN_ITEMS_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_ALIGN_ITEMS_CENTER_",
      value: "a_align_items_center",
      group: "flex",
      groupName: "_A_SELECT_STYLES_GROUP_FLEX_",
      subGroup: "align_items",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_ALIGN_ITEMS_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_ALIGN_ITEMS_BASELINE_",
      value: "a_align_items_baseline",
      group: "flex",
      groupName: "_A_SELECT_STYLES_GROUP_FLEX_",
      subGroup: "align_items",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_ALIGN_ITEMS_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_ALIGN_ITEMS_STRETCH_",
      value: "a_align_items_stretch",
      group: "flex",
      groupName: "_A_SELECT_STYLES_GROUP_FLEX_",
      subGroup: "align_items",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_ALIGN_ITEMS_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_ALIGN_SELF_AUTO_",
      value: "a_align_self_auto",
      group: "flex",
      groupName: "_A_SELECT_STYLES_GROUP_FLEX_",
      subGroup: "align_self",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_ALIGN_SELF_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_ALIGN_SELF_START_",
      value: "a_align_self_start",
      group: "flex",
      groupName: "_A_SELECT_STYLES_GROUP_FLEX_",
      subGroup: "align_self",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_ALIGN_SELF_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_ALIGN_SELF_END_",
      value: "a_align_self_end",
      group: "flex",
      groupName: "_A_SELECT_STYLES_GROUP_FLEX_",
      subGroup: "align_self",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_ALIGN_SELF_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_ALIGN_SELF_CENTER_",
      value: "a_align_self_center",
      group: "flex",
      groupName: "_A_SELECT_STYLES_GROUP_FLEX_",
      subGroup: "align_self",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_ALIGN_SELF_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_ALIGN_SELF_BASELINE_",
      value: "a_align_self_baseline",
      group: "flex",
      groupName: "_A_SELECT_STYLES_GROUP_FLEX_",
      subGroup: "align_self",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_ALIGN_SELF_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_ALIGN_SELF_STRETCH_",
      value: "a_align_self_stretch",
      group: "flex",
      groupName: "_A_SELECT_STYLES_GROUP_FLEX_",
      subGroup: "align_self",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_ALIGN_SELF_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_JUSTIFY_SELF_AUTO_",
      value: "a_justify_self_auto",
      group: "flex",
      groupName: "_A_SELECT_STYLES_GROUP_FLEX_",
      subGroup: "justify_self",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_JUSTIFY_SELF_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_JUSTIFY_SELF_START_",
      value: "a_justify_self_start",
      group: "flex",
      groupName: "_A_SELECT_STYLES_GROUP_FLEX_",
      subGroup: "justify_self",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_JUSTIFY_SELF_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_JUSTIFY_SELF_END_",
      value: "a_justify_self_end",
      group: "flex",
      groupName: "_A_SELECT_STYLES_GROUP_FLEX_",
      subGroup: "justify_self",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_JUSTIFY_SELF_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_JUSTIFY_SELF_CENTER_",
      value: "a_justify_self_center",
      group: "flex",
      groupName: "_A_SELECT_STYLES_GROUP_FLEX_",
      subGroup: "justify_self",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_JUSTIFY_SELF_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_JUSTIFY_SELF_BASELINE_",
      value: "a_justify_self_baseline",
      group: "flex",
      groupName: "_A_SELECT_STYLES_GROUP_FLEX_",
      subGroup: "justify_self",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_JUSTIFY_SELF_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_JUSTIFY_SELF_STRETCH_",
      value: "a_justify_self_stretch",
      group: "flex",
      groupName: "_A_SELECT_STYLES_GROUP_FLEX_",
      subGroup: "justify_self",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_JUSTIFY_SELF_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_FLEX_WRAP_",
      value: "a_flex_wrap",
      group: "flex",
      groupName: "_A_SELECT_STYLES_GROUP_FLEX_",
      subGroup: "flex_wrap",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_FLEX_WRAP_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_FLEX_NOWRAP_",
      value: "a_flex_nowrap",
      group: "flex",
      groupName: "_A_SELECT_STYLES_GROUP_FLEX_",
      subGroup: "flex_wrap",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_FLEX_WRAP_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_FLEX_WRAP_REVERSE_",
      value: "a_flex_wrap_reverse",
      group: "flex",
      groupName: "_A_SELECT_STYLES_GROUP_FLEX_",
      subGroup: "flex_wrap",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_FLEX_WRAP_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_ALIGN_CONTENT_START_",
      value: "a_align_content_start",
      group: "flex",
      groupName: "_A_SELECT_STYLES_GROUP_FLEX_",
      subGroup: "align_content",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_ALIGN_CONTENT_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_ALIGN_CONTENT_END_",
      value: "a_align_content_end",
      group: "flex",
      groupName: "_A_SELECT_STYLES_GROUP_FLEX_",
      subGroup: "align_content",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_ALIGN_CONTENT_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_ALIGN_CONTENT_CENTER_",
      value: "a_align_content_center",
      group: "flex",
      groupName: "_A_SELECT_STYLES_GROUP_FLEX_",
      subGroup: "align_content",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_ALIGN_CONTENT_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_ALIGN_CONTENT_BETWEEN_",
      value: "a_align_content_between",
      group: "flex",
      groupName: "_A_SELECT_STYLES_GROUP_FLEX_",
      subGroup: "align_content",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_ALIGN_CONTENT_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_ALIGN_CONTENT_AROUND_",
      value: "a_align_content_around",
      group: "flex",
      groupName: "_A_SELECT_STYLES_GROUP_FLEX_",
      subGroup: "align_content",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_ALIGN_CONTENT_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_ALIGN_CONTENT_STRETCH_",
      value: "a_align_content_stretch",
      group: "flex",
      groupName: "_A_SELECT_STYLES_GROUP_FLEX_",
      subGroup: "align_content",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_ALIGN_CONTENT_",
    },

    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_LEFT_",
      value: "a_text_left",
      group: "text_align",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_ALIGN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_LEFT_",
      value: "a_text_left_mobile",
      group: "text_align",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_ALIGN_",
      subGroup: "mobile",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_MOBILE_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_LEFT_",
      value: "a_text_left_tablet",
      group: "text_align",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_ALIGN_",
      subGroup: "tablet",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_TABLET_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_LEFT_",
      value: "a_text_left_touch",
      group: "text_align",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_ALIGN_",
      subGroup: "touch",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_TOUCH_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_LEFT_",
      value: "a_text_left_desktop",
      group: "text_align",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_ALIGN_",
      subGroup: "desktop",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_DESKTOP_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_LEFT_",
      value: "a_text_left_widescreen",
      group: "text_align",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_ALIGN_",
      subGroup: "widescreen",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_WIDESCREEN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_LEFT_",
      value: "a_text_left_fullhd",
      group: "text_align",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_ALIGN_",
      subGroup: "fullhd",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_FULLHD_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_LEFT_",
      value: "a_text_left_large",
      group: "text_align",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_ALIGN_",
      subGroup: "large",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_LARGE_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_CENTER_",
      value: "a_text_center",
      group: "text_align",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_ALIGN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_CENTER_",
      value: "a_text_center_mobile",
      group: "text_align",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_ALIGN_",
      subGroup: "mobile",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_MOBILE_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_CENTER_",
      value: "a_text_center_tablet",
      group: "text_align",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_ALIGN_",
      subGroup: "tablet",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_TABLET_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_CENTER_",
      value: "a_text_center_touch",
      group: "text_align",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_ALIGN_",
      subGroup: "touch",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_TOUCH_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_CENTER_",
      value: "a_text_center_desktop",
      group: "text_align",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_ALIGN_",
      subGroup: "desktop",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_DESKTOP_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_CENTER_",
      value: "a_text_center_widescreen",
      group: "text_align",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_ALIGN_",
      subGroup: "widescreen",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_WIDESCREEN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_CENTER_",
      value: "a_text_center_fullhd",
      group: "text_align",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_ALIGN_",
      subGroup: "fullhd",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_FULLHD_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_CENTER_",
      value: "a_text_center_large",
      group: "text_align",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_ALIGN_",
      subGroup: "large",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_LARGE_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_RIGHT_",
      value: "a_text_right",
      group: "text_align",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_ALIGN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_RIGHT_",
      value: "a_text_right_mobile",
      group: "text_align",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_ALIGN_",
      subGroup: "mobile",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_MOBILE_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_RIGHT_",
      value: "a_text_right_tablet",
      group: "text_align",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_ALIGN_",
      subGroup: "tablet",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_TABLET_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_RIGHT_",
      value: "a_text_right_touch",
      group: "text_align",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_ALIGN_",
      subGroup: "touch",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_TOUCH_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_RIGHT_",
      value: "a_text_right_desktop",
      group: "text_align",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_ALIGN_",
      subGroup: "desktop",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_DESKTOP_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_RIGHT_",
      value: "a_text_right_widescreen",
      group: "text_align",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_ALIGN_",
      subGroup: "widescreen",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_WIDESCREEN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_RIGHT_",
      value: "a_text_right_fullhd",
      group: "text_align",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_ALIGN_",
      subGroup: "fullhd",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_FULLHD_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_RIGHT_",
      value: "a_text_right_large",
      group: "text_align",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_ALIGN_",
      subGroup: "large",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_LARGE_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_JUSTIFY_",
      value: "a_text_justify",
      group: "text_align",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_ALIGN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_JUSTIFY_",
      value: "a_text_justify_mobile",
      group: "text_align",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_ALIGN_",
      subGroup: "mobile",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_MOBILE_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_JUSTIFY_",
      value: "a_text_justify_tablet",
      group: "text_align",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_ALIGN_",
      subGroup: "tablet",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_TABLET_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_JUSTIFY_",
      value: "a_text_justify_touch",
      group: "text_align",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_ALIGN_",
      subGroup: "touch",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_TOUCH_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_JUSTIFY_",
      value: "a_text_justify_desktop",
      group: "text_align",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_ALIGN_",
      subGroup: "desktop",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_DESKTOP_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_JUSTIFY_",
      value: "a_text_justify_widescreen",
      group: "text_align",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_ALIGN_",
      subGroup: "widescreen",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_WIDESCREEN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_JUSTIFY_",
      value: "a_text_justify_fullhd",
      group: "text_align",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_ALIGN_",
      subGroup: "fullhd",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_FULLHD_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_JUSTIFY_",
      value: "a_text_justify_large",
      group: "text_align",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_ALIGN_",
      subGroup: "large",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_LARGE_",
    },

    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_WRAP_",
      value: "a_text_wrap",
      group: "text_wrapping",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_WRAPPING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_NOWRAP_",
      value: "a_text_nowrap",
      group: "text_wrapping",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_WRAPPING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_BREAK_",
      value: "a_text_break",
      group: "text_wrapping",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_WRAPPING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_WRAP_HYPHENS_",
      value: "a_text_wrap_hyphens",
      group: "text_wrapping",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_WRAPPING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_TRUNCATE_",
      value: "a_text_truncate",
      group: "text_wrapping",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_WRAPPING_",
    },

    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_CLAMP_",
      value: "a_text_clamp",
      group: "line_limiting",
      groupName: "_A_SELECT_STYLES_GROUP_LINE_LIMITING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_CLAMP_2_",
      value: "a_text_clamp a_text_clamp_2",
      group: "line_limiting",
      groupName: "_A_SELECT_STYLES_GROUP_LINE_LIMITING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_CLAMP_3_",
      value: "a_text_clamp a_text_clamp_3",
      group: "line_limiting",
      groupName: "_A_SELECT_STYLES_GROUP_LINE_LIMITING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_CLAMP_4_",
      value: "a_text_clamp a_text_clamp_4",
      group: "line_limiting",
      groupName: "_A_SELECT_STYLES_GROUP_LINE_LIMITING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_CLAMP_5_",
      value: "a_text_clamp a_text_clamp_5",
      group: "line_limiting",
      groupName: "_A_SELECT_STYLES_GROUP_LINE_LIMITING_",
    },

    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_LOWERCASE_",
      value: "a_text_lowercase",
      group: "text_transform",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_TRANSFORM_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_UPPERCASE_",
      value: "a_text_uppercase",
      group: "text_transform",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_TRANSFORM_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_CAPITALIZE_",
      value: "a_text_capitalize",
      group: "text_transform",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_TRANSFORM_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_UNDERLINE_",
      value: "a_text_underline",
      group: "text_transform",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_TRANSFORM_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_LINE_THROUGH_",
      value: "a_text_line_through",
      group: "text_transform",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_TRANSFORM_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_DECORATION_NONE_",
      value: "a_text_decoration_none",
      group: "text_transform",
      groupName: "_A_SELECT_STYLES_GROUP_TEXT_TRANSFORM_",
    },


    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_BOLD_",
      value: "a_text_bold",
      group: "font_weight",
      groupName: "_A_SELECT_STYLES_GROUP_FONT_WEIGHT_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_BOLDER_",
      value: "a_text_bolder",
      group: "font_weight",
      groupName: "_A_SELECT_STYLES_GROUP_FONT_WEIGHT_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_SEMIBOLD_",
      value: "a_text_semibold",
      group: "font_weight",
      groupName: "_A_SELECT_STYLES_GROUP_FONT_WEIGHT_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_LIGHT_",
      value: "a_text_light",
      group: "font_weight",
      groupName: "_A_SELECT_STYLES_GROUP_FONT_WEIGHT_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_LIGHTER_",
      value: "a_text_lighter",
      group: "font_weight",
      groupName: "_A_SELECT_STYLES_GROUP_FONT_WEIGHT_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_ITALIC_",
      value: "a_text_italic",
      group: "font_weight",
      groupName: "_A_SELECT_STYLES_GROUP_FONT_WEIGHT_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_TEXT_NORMAL_",
      value: "a_text_normal",
      group: "font_weight",
      groupName: "_A_SELECT_STYLES_GROUP_FONT_WEIGHT_",
    },


    {
      label: "_A_SELECT_STYLES_VALUE_LINE_HEIGHT_1_",
      value: "a_line_height_1",
      group: "line_height",
      groupName: "_A_SELECT_STYLES_GROUP_LINE_HEIGHT_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_LINE_HEIGHT_SMALL_",
      value: "a_line_height_small",
      group: "line_height",
      groupName: "_A_SELECT_STYLES_GROUP_LINE_HEIGHT_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_LINE_HEIGHT_BASE_",
      value: "a_line_height_base",
      group: "line_height",
      groupName: "_A_SELECT_STYLES_GROUP_LINE_HEIGHT_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_LINE_HEIGHT_LARGE_",
      value: "a_line_height_large",
      group: "line_height",
      groupName: "_A_SELECT_STYLES_GROUP_LINE_HEIGHT_",
    },

    {
      label: "_A_SELECT_STYLES_VALUE_FS_1_",
      value: "a_fs_1",
      group: "font_size",
      groupName: "_A_SELECT_STYLES_GROUP_FONT_SIZE_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_FS_2_",
      value: "a_fs_2",
      group: "font_size",
      groupName: "_A_SELECT_STYLES_GROUP_FONT_SIZE_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_FS_3_",
      value: "a_fs_3",
      group: "font_size",
      groupName: "_A_SELECT_STYLES_GROUP_FONT_SIZE_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_FS_4_",
      value: "a_fs_4",
      group: "font_size",
      groupName: "_A_SELECT_STYLES_GROUP_FONT_SIZE_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_FS_5_",
      value: "a_fs_5",
      group: "font_size",
      groupName: "_A_SELECT_STYLES_GROUP_FONT_SIZE_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_FS_6_",
      value: "a_fs_6",
      group: "font_size",
      groupName: "_A_SELECT_STYLES_GROUP_FONT_SIZE_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_FS_7_",
      value: "a_fs_7",
      group: "font_size",
      groupName: "_A_SELECT_STYLES_GROUP_FONT_SIZE_",
    },

    {
      label: "_A_SELECT_STYLES_VALUE_M_1_",
      value: "a_m_1",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_MT_1_",
      value: "a_mt_1",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_MR_1_",
      value: "a_mr_1",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_MB_1_",
      value: "a_mb_1",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_ML_1_",
      value: "a_ml_1",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_MX_1_",
      value: "a_mx_1",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_MY_1_",
      value: "a_my_1",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_M_2_",
      value: "a_m_2",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_MT_2_",
      value: "a_mt_2",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_MR_2_",
      value: "a_mr_2",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_MB_2_",
      value: "a_mb_2",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_ML_2_",
      value: "a_ml_2",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_MX_2_",
      value: "a_mx_2",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_MY_2_",
      value: "a_my_2",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_M_3_",
      value: "a_m_3",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_MT_3_",
      value: "a_mt_3",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_MR_3_",
      value: "a_mr_3",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_MB_3_",
      value: "a_mb_3",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_ML_3_",
      value: "a_ml_3",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_MX_3_",
      value: "a_mx_3",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_MY_3_",
      value: "a_my_3",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_M_4_",
      value: "a_m_4",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_MT_4_",
      value: "a_mt_4",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_MR_4_",
      value: "a_mr_4",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_MB_4_",
      value: "a_mb_4",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_ML_4_",
      value: "a_ml_4",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_MX_4_",
      value: "a_mx_4",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_MY_4_",
      value: "a_my_4",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_M_5_",
      value: "a_m_5",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_MT_5_",
      value: "a_mt_5",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_MR_5_",
      value: "a_mr_5",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_MB_5_",
      value: "a_mb_5",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_ML_5_",
      value: "a_ml_5",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_MX_5_",
      value: "a_mx_5",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_MY_5_",
      value: "a_my_5",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_M_6_",
      value: "a_m_6",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_MT_6_",
      value: "a_mt_6",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_MR_6_",
      value: "a_mr_6",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_MB_6_",
      value: "a_mb_6",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_ML_6_",
      value: "a_ml_6",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_MX_6_",
      value: "a_mx_6",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_MY_6_",
      value: "a_my_6",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_M_AUTO_",
      value: "a_m_auto",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_MT_AUTO_",
      value: "a_mt_auto",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_MR_AUTO_",
      value: "a_mr_auto",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_MB_AUTO_",
      value: "a_mb_auto",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_ML_AUTO_",
      value: "a_ml_auto",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_MX_AUTO_",
      value: "a_mx_auto",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_MY_AUTO_",
      value: "a_my_auto",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_M_0_",
      value: "a_m_0",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_MT_0_",
      value: "a_mt_0",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_MR_0_",
      value: "a_mr_0",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_MB_0_",
      value: "a_mb_0",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_ML_0_",
      value: "a_ml_0",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_MX_0_",
      value: "a_mx_0",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_MY_0_",
      value: "a_my_0",
      group: "margin",
      groupName: "_A_SELECT_STYLES_GROUP_MARGIN_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_P_1_",
      value: "a_p_1",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PT_1_",
      value: "a_pt_1",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PR_1_",
      value: "a_pr_1",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PB_1_",
      value: "a_pb_1",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PL_1_",
      value: "a_pl_1",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PX_1_",
      value: "a_px_1",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PY_1_",
      value: "a_py_1",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_P_2_",
      value: "a_p_2",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PT_2_",
      value: "a_pt_2",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PR_2_",
      value: "a_pr_2",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PB_2_",
      value: "a_pb_2",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PL_2_",
      value: "a_pl_2",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PX_2_",
      value: "a_px_2",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PY_2_",
      value: "a_py_2",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_P_3_",
      value: "a_p_3",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PT_3_",
      value: "a_pt_3",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PR_3_",
      value: "a_pr_3",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PB_3_",
      value: "a_pb_3",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PL_3_",
      value: "a_pl_3",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PX_3_",
      value: "a_px_3",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PY_3_",
      value: "a_py_3",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_P_4_",
      value: "a_p_4",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PT_4_",
      value: "a_pt_4",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PR_4_",
      value: "a_pr_4",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PB_4_",
      value: "a_pb_4",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PL_4_",
      value: "a_pl_4",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PX_4_",
      value: "a_px_4",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PY_4_",
      value: "a_py_4",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_P_5_",
      value: "a_p_5",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PT_5_",
      value: "a_pt_5",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PR_5_",
      value: "a_pr_5",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PB_5_",
      value: "a_pb_5",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PL_5_",
      value: "a_pl_5",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PX_5_",
      value: "a_px_5",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PY_5_",
      value: "a_py_5",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_P_6_",
      value: "a_p_6",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PT_6_",
      value: "a_pt_6",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PR_6_",
      value: "a_pr_6",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PB_6_",
      value: "a_pb_6",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PL_6_",
      value: "a_pl_6",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PX_6_",
      value: "a_px_6",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PY_6_",
      value: "a_py_6",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_P_AUTO_",
      value: "a_p_auto",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PT_AUTO_",
      value: "a_pt_auto",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PR_AUTO_",
      value: "a_pr_auto",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PB_AUTO_",
      value: "a_pb_auto",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PL_AUTO_",
      value: "a_pl_auto",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PX_AUTO_",
      value: "a_px_auto",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PY_AUTO_",
      value: "a_py_auto",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_P_0_",
      value: "a_p_0",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PT_0_",
      value: "a_pt_0",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PR_0_",
      value: "a_pr_0",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PB_0_",
      value: "a_pb_0",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PL_0_",
      value: "a_pl_0",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PX_0_",
      value: "a_px_0",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_PY_0_",
      value: "a_py_0",
      group: "padding",
      groupName: "_A_SELECT_STYLES_GROUP_PADDING_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_COLOR_PRIMARY_",
      value: "a_color_primary",
      group: "color",
      groupName: "_A_SELECT_STYLES_GROUP_COLOR_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_COLOR_SECONDARY_",
      value: "a_color_secondary",
      group: "color",
      groupName: "_A_SELECT_STYLES_GROUP_COLOR_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_COLOR_TERTIARY_",
      value: "a_color_tertiary",
      group: "color",
      groupName: "_A_SELECT_STYLES_GROUP_COLOR_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_COLOR_TEXT_",
      value: "a_color_text",
      group: "color",
      groupName: "_A_SELECT_STYLES_GROUP_COLOR_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_COLOR_INFO_",
      value: "a_color_info",
      group: "color",
      groupName: "_A_SELECT_STYLES_GROUP_COLOR_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_COLOR_SUCCESS_",
      value: "a_color_success",
      group: "color",
      groupName: "_A_SELECT_STYLES_GROUP_COLOR_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_COLOR_WARNING_",
      value: "a_color_warning",
      group: "color",
      groupName: "_A_SELECT_STYLES_GROUP_COLOR_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_COLOR_DANGER_",
      value: "a_color_danger",
      group: "color",
      groupName: "_A_SELECT_STYLES_GROUP_COLOR_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_COLOR_LINK_",
      value: "a_color_link",
      group: "color",
      groupName: "_A_SELECT_STYLES_GROUP_COLOR_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_COLOR_WHITE_",
      value: "a_color_white",
      group: "color",
      groupName: "_A_SELECT_STYLES_GROUP_COLOR_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_COLOR_BLACK_",
      value: "a_color_black",
      group: "color",
      groupName: "_A_SELECT_STYLES_GROUP_COLOR_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_COLOR_GRAY_100_",
      value: "a_color_gray_100",
      group: "color",
      groupName: "_A_SELECT_STYLES_GROUP_COLOR_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_COLOR_GRAY_200_",
      value: "a_color_gray_200",
      group: "color",
      groupName: "_A_SELECT_STYLES_GROUP_COLOR_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_COLOR_GRAY_300_",
      value: "a_color_gray_300",
      group: "color",
      groupName: "_A_SELECT_STYLES_GROUP_COLOR_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_COLOR_GRAY_400_",
      value: "a_color_gray_400",
      group: "color",
      groupName: "_A_SELECT_STYLES_GROUP_COLOR_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_COLOR_GRAY_500_",
      value: "a_color_gray_500",
      group: "color",
      groupName: "_A_SELECT_STYLES_GROUP_COLOR_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_COLOR_GRAY_600_",
      value: "a_color_gray_600",
      group: "color",
      groupName: "_A_SELECT_STYLES_GROUP_COLOR_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_COLOR_GRAY_700_",
      value: "a_color_gray_700",
      group: "color",
      groupName: "_A_SELECT_STYLES_GROUP_COLOR_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_COLOR_GRAY_800_",
      value: "a_color_gray_800",
      group: "color",
      groupName: "_A_SELECT_STYLES_GROUP_COLOR_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_COLOR_GRAY_900_",
      value: "a_color_gray_900",
      group: "color",
      groupName: "_A_SELECT_STYLES_GROUP_COLOR_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_COLOR_TRANSPARENT_",
      value: "a_color_transparent",
      group: "color",
      groupName: "_A_SELECT_STYLES_GROUP_COLOR_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BG_PRIMARY_",
      value: "a_bg_primary",
      group: "background_color",
      groupName: "_A_SELECT_STYLES_GROUP_BACKGROUND_COLOR_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BG_SECONDARY_",
      value: "a_bg_secondary",
      group: "background_color",
      groupName: "_A_SELECT_STYLES_GROUP_BACKGROUND_COLOR_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BG_TERTIARY_",
      value: "a_bg_tertiary",
      group: "background_color",
      groupName: "_A_SELECT_STYLES_GROUP_BACKGROUND_COLOR_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BG_TEXT_",
      value: "a_bg_text",
      group: "background_color",
      groupName: "_A_SELECT_STYLES_GROUP_BACKGROUND_COLOR_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BG_INFO_",
      value: "a_bg_info",
      group: "background_color",
      groupName: "_A_SELECT_STYLES_GROUP_BACKGROUND_COLOR_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BG_SUCCESS_",
      value: "a_bg_success",
      group: "background_color",
      groupName: "_A_SELECT_STYLES_GROUP_BACKGROUND_COLOR_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BG_WARNING_",
      value: "a_bg_warning",
      group: "background_color",
      groupName: "_A_SELECT_STYLES_GROUP_BACKGROUND_COLOR_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BG_DANGER_",
      value: "a_bg_danger",
      group: "background_color",
      groupName: "_A_SELECT_STYLES_GROUP_BACKGROUND_COLOR_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BG_LINK_",
      value: "a_bg_link",
      group: "background_color",
      groupName: "_A_SELECT_STYLES_GROUP_BACKGROUND_COLOR_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BG_WHITE_",
      value: "a_bg_white",
      group: "background_color",
      groupName: "_A_SELECT_STYLES_GROUP_BACKGROUND_COLOR_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BG_BLACK_",
      value: "a_bg_black",
      group: "background_color",
      groupName: "_A_SELECT_STYLES_GROUP_BACKGROUND_COLOR_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BG_GRAY_100_",
      value: "a_bg_gray_100",
      group: "background_color",
      groupName: "_A_SELECT_STYLES_GROUP_BACKGROUND_COLOR_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BG_GRAY_200_",
      value: "a_bg_gray_200",
      group: "background_color",
      groupName: "_A_SELECT_STYLES_GROUP_BACKGROUND_COLOR_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BG_GRAY_300_",
      value: "a_bg_gray_300",
      group: "background_color",
      groupName: "_A_SELECT_STYLES_GROUP_BACKGROUND_COLOR_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BG_GRAY_400_",
      value: "a_bg_gray_400",
      group: "background_color",
      groupName: "_A_SELECT_STYLES_GROUP_BACKGROUND_COLOR_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BG_GRAY_500_",
      value: "a_bg_gray_500",
      group: "background_color",
      groupName: "_A_SELECT_STYLES_GROUP_BACKGROUND_COLOR_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BG_GRAY_600_",
      value: "a_bg_gray_600",
      group: "background_color",
      groupName: "_A_SELECT_STYLES_GROUP_BACKGROUND_COLOR_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BG_GRAY_700_",
      value: "a_bg_gray_700",
      group: "background_color",
      groupName: "_A_SELECT_STYLES_GROUP_BACKGROUND_COLOR_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BG_GRAY_800_",
      value: "a_bg_gray_800",
      group: "background_color",
      groupName: "_A_SELECT_STYLES_GROUP_BACKGROUND_COLOR_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BG_GRAY_900_",
      value: "a_bg_gray_900",
      group: "background_color",
      groupName: "_A_SELECT_STYLES_GROUP_BACKGROUND_COLOR_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BG_TRANSPARENT_",
      value: "a_bg_transparent",
      group: "background_color",
      groupName: "_A_SELECT_STYLES_GROUP_BACKGROUND_COLOR_",
    },

    {
      label: "_A_SELECT_STYLES_VALUE_BTN_PRIMARY_",
      value: "a_btn a_btn_primary",
      group: "button",
      groupName: "_A_SELECT_STYLES_GROUP_BUTTON_",
      subGroup: "basic",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_BASIC_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BTN_SECONDARY_",
      value: "a_btn a_btn_secondary",
      group: "button",
      groupName: "_A_SELECT_STYLES_GROUP_BUTTON_",
      subGroup: "basic",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_BASIC_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BTN_TERTIARY_",
      value: "a_btn a_btn_tertiary",
      group: "button",
      groupName: "_A_SELECT_STYLES_GROUP_BUTTON_",
      subGroup: "basic",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_BASIC_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BTN_SUCCESS_",
      value: "a_btn a_btn_success",
      group: "button",
      groupName: "_A_SELECT_STYLES_GROUP_BUTTON_",
      subGroup: "basic",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_BASIC_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BTN_INFO_",
      value: "a_btn a_btn_info",
      group: "button",
      groupName: "_A_SELECT_STYLES_GROUP_BUTTON_",
      subGroup: "basic",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_BASIC_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BTN_WARNING_",
      value: "a_btn a_btn_warning",
      group: "button",
      groupName: "_A_SELECT_STYLES_GROUP_BUTTON_",
      subGroup: "basic",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_BASIC_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BTN_DANGER_",
      value: "a_btn a_btn_danger",
      group: "button",
      groupName: "_A_SELECT_STYLES_GROUP_BUTTON_",
      subGroup: "basic",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_BASIC_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BTN_LIGHT_",
      value: "a_btn a_btn_light",
      group: "button",
      groupName: "_A_SELECT_STYLES_GROUP_BUTTON_",
      subGroup: "basic",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_BASIC_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BTN_DARK_",
      value: "a_btn a_btn_dark",
      group: "button",
      groupName: "_A_SELECT_STYLES_GROUP_BUTTON_",
      subGroup: "basic",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_BASIC_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BTN_LINK_",
      value: "a_btn a_btn_link",
      group: "button",
      groupName: "_A_SELECT_STYLES_GROUP_BUTTON_",
      subGroup: "basic",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_BASIC_",
    },

    {
      label: "_A_SELECT_STYLES_VALUE_BTN_PRIMARY_",
      value: "a_btn a_btn_outline_primary",
      group: "button",
      groupName: "_A_SELECT_STYLES_GROUP_BUTTON_",
      subGroup: "outline",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_OUTLINE_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BTN_SECONDARY_",
      value: "a_btn a_btn_outline_secondary",
      group: "button",
      groupName: "_A_SELECT_STYLES_GROUP_BUTTON_",
      subGroup: "outline",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_OUTLINE_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BTN_TERTIARY_",
      value: "a_btn a_btn_outline_tertiary",
      group: "button",
      groupName: "_A_SELECT_STYLES_GROUP_BUTTON_",
      subGroup: "outline",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_OUTLINE_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BTN_SUCCESS_",
      value: "a_btn a_btn_outline_success",
      group: "button",
      groupName: "_A_SELECT_STYLES_GROUP_BUTTON_",
      subGroup: "outline",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_OUTLINE_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BTN_INFO_",
      value: "a_btn a_btn_outline_info",
      group: "button",
      groupName: "_A_SELECT_STYLES_GROUP_BUTTON_",
      subGroup: "outline",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_OUTLINE_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BTN_WARNING_",
      value: "a_btn a_btn_outline_warning",
      group: "button",
      groupName: "_A_SELECT_STYLES_GROUP_BUTTON_",
      subGroup: "outline",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_OUTLINE_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BTN_DANGER_",
      value: "a_btn a_btn_outline_danger",
      group: "button",
      groupName: "_A_SELECT_STYLES_GROUP_BUTTON_",
      subGroup: "outline",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_OUTLINE_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BTN_LIGHT_",
      value: "a_btn a_btn_outline_light",
      group: "button",
      groupName: "_A_SELECT_STYLES_GROUP_BUTTON_",
      subGroup: "outline",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_OUTLINE_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BTN_DARK_",
      value: "a_btn a_btn_outline_dark",
      group: "button",
      groupName: "_A_SELECT_STYLES_GROUP_BUTTON_",
      subGroup: "outline",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_OUTLINE_",
    },

    {
      label: "_A_SELECT_STYLES_VALUE_BTN_PRIMARY_",
      value: "a_btn a_btn_transparent_primary",
      group: "button",
      groupName: "_A_SELECT_STYLES_GROUP_BUTTON_",
      subGroup: "transparent",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_TRANSPARENT_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BTN_SECONDARY_",
      value: "a_btn a_btn_transparent_secondary",
      group: "button",
      groupName: "_A_SELECT_STYLES_GROUP_BUTTON_",
      subGroup: "transparent",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_TRANSPARENT_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BTN_TERTIARY_",
      value: "a_btn a_btn_transparent_tertiary",
      group: "button",
      groupName: "_A_SELECT_STYLES_GROUP_BUTTON_",
      subGroup: "transparent",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_TRANSPARENT_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BTN_SUCCESS_",
      value: "a_btn a_btn_transparent_success",
      group: "button",
      groupName: "_A_SELECT_STYLES_GROUP_BUTTON_",
      subGroup: "transparent",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_TRANSPARENT_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BTN_INFO_",
      value: "a_btn a_btn_transparent_info",
      group: "button",
      groupName: "_A_SELECT_STYLES_GROUP_BUTTON_",
      subGroup: "transparent",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_TRANSPARENT_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BTN_WARNING_",
      value: "a_btn a_btn_transparent_warning",
      group: "button",
      groupName: "_A_SELECT_STYLES_GROUP_BUTTON_",
      subGroup: "transparent",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_TRANSPARENT_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BTN_DANGER_",
      value: "a_btn a_btn_transparent_danger",
      group: "button",
      groupName: "_A_SELECT_STYLES_GROUP_BUTTON_",
      subGroup: "transparent",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_TRANSPARENT_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BTN_LIGHT_",
      value: "a_btn a_btn_transparent_light",
      group: "button",
      groupName: "_A_SELECT_STYLES_GROUP_BUTTON_",
      subGroup: "transparent",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_TRANSPARENT_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BTN_DARK_",
      value: "a_btn a_btn_transparent_dark",
      group: "button",
      groupName: "_A_SELECT_STYLES_GROUP_BUTTON_",
      subGroup: "transparent",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_TRANSPARENT_",
    },

    {
      label: "_A_SELECT_STYLES_VALUE_BTN_LARGE_",
      value: "a_btn a_btn_large",
      group: "button",
      groupName: "_A_SELECT_STYLES_GROUP_BUTTON_",
      subGroup: "size",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_SIZE_",
    },
    {
      label: "_A_SELECT_STYLES_VALUE_BTN_SMALL_",
      value: "a_btn a_btn_small",
      group: "button",
      groupName: "_A_SELECT_STYLES_GROUP_BUTTON_",
      subGroup: "size",
      subGroupName: "_A_SELECT_STYLES_SUB_GROUP_SIZE_",
    },
  ],
};


export default {
  install: (app, {
    propsDefault = {},
    cssClasses = [],
  } = {}) => {
    ASelectStylePluginOptions.propsDefault = {
      ...ASelectStylePluginOptions.propsDefault,
      ...propsDefault,
    };
    ASelectStylePluginOptions.cssClasses = [
      ...ASelectStylePluginOptions.cssClasses,
      ...cssClasses,
    ];
  },
};
